# Generated by Django 4.2.2 on 2023-06-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='uid',
            field=models.CharField(default='default_value_here', max_length=255),
        ),
    ]
